api/config/routes.rb
# typed: false

require "sidekiq/web"

Rails.application.routes.draw do
  root "dashboard#show"

  devise_for :users, controllers: { registrations: "users/registrations" }

  scope module: :relay do
    scope module: :api, defaults: { format: :json } do
      scope path: "v1" do
        namespace :helium do
          namespace :l1 do
            resources :accounts, only: [ :index, :show ]
            resources :transactions, only: [ :index, :show ]
            resources :transaction_actors, only: [ :index ], path: "transaction-actors"
            resources :dc_burns, only: [ :index ], path: "dc-burns"
            resources :gateways, only: [ :index, :show ]
            resources :packets, only: [ :index ]
            resources :rewards, only: [ :index ]
          end

          namespace :l2 do
            resources :iot_reward_shares, only: [ :index ], path: "iot-reward-shares" do
              collection do
                get :totals
              end
            end
            resources :mobile_reward_shares, only: [ :index ], path: "mobile-reward-shares" do
              collection do
                get :totals
              end
            end
            resources :makers, only: [ :index, :show ]
            resources :hotspots, only: [ :index, :show ]
          end
        end
      end
    end

    namespace :webhooks do
      post "helius" => "webhooks#create", source: "helius"
      post "stripe" => "webhooks#create", source: "stripe"
    end
  end

  get "/billing" => "dashboard#billing_portal", as: :billing_portal
  post "/subscribe/:plan_id" => "dashboard#subscribe", as: :subscribe

  get "up" => "rails/health#show", as: :rails_health_check

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV.fetch("SIDEKIQ_USERNAME"))
    ) & ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(ENV.fetch("SIDEKIQ_PASSWORD"))
    )
  end
  mount Sidekiq::Web => "/sidekiq"
end

api/app/controllers/dashboard_controller.rb
# typed: false

class DashboardController < ApplicationController
  extend T::Sig

  before_action :authenticate_user!

  sig { void }
  def show
  end

  sig { void }
  def subscribe
    plan = Relay::Billing::Plan.find!(params.fetch(:plan_id))

    if plan.custom_pricing?
      redirect_back(fallback_location: root_url)
      return
    end

    if plan.free?
      unless current_user.payment_processor.subscribed?
        redirect_back(fallback_location: root_url)
        return
      end

      current_user.payment_processor.subscription.cancel
      redirect_back(fallback_location: root_url)

      return
    end

    if current_user.payment_processor.subscribed?
      current_user.payment_processor.subscription.swap(plan.stripe_price.id)
      redirect_to root_url
    else
      session = current_user.payment_processor.checkout(
        mode: "subscription",
        line_items: [ {
          price: plan.stripe_price.id,
          quantity: 1
        } ],
        success_url: root_url,
        cancel_url: root_url
      )

      redirect_to session.url, allow_other_host: true
    end
  end

  sig { void }
  def billing_portal
    portal_session = current_user.payment_processor.billing_portal

    redirect_to portal_session.url, allow_other_host: true
  end
end

api/app/views/dashboard/show.html.erb
<% content_for :title, "Dashboard" %>

<div class="space-y-4">
  <%= render(CardComponent.new(
    title: "The Relay API is in beta!",
    color: :amber
  )) do %>
    <p class="text-gray-600">The API might have issues, bugs, and imperfections. We welcome any feedback in our official Helium Discord channel.</p>
  <% end %>

  <%= render(CardComponent.new(title: "Getting Started")) do %>
    <p class="text-gray-600 mb-6">Welcome to the Relay GraphQL API for Helium Oracle data! This API allows you to easily query information about any Helium hotspot, including essential details, earnings, and historical data.</p>

    <div class="flex gap-4">
      <%= render(ButtonComponent.new(
        text: "Read Docs",
        style: :secondary,
        href: "https://docs.relaywireless.com",
        target: "_blank"
      )) %>
      <%= render(ButtonComponent.new(
        text: "Join Relay Discord",
        style: :secondary,
        href: "https://discord.com/channels/404106811252408320/1368978610907513042",
        target: "_blank"
      )) %>
    </div>
  <% end %>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <%= render(CardComponent.new(title: "API Key")) do %>
      <p class="text-gray-600 mb-4">This is your API key for accessing the Relay API.</p>
      <%= render(CopiableTextComponent.new(text: current_user.api_key)) %>
    <% end %>

    <%= render(CardComponent.new(title: "Usage")) do %>
      <%= render(PlanUsageComponent.new(user: current_user)) %>
    <% end %>
  </div>

  <% if current_user.feature_gater.enabled?(:billing) %>
    <div class="space-y-4">
      <div class="text-2xl font-bold">Billing</div>

      <%= render FlashMessageComponent.new(type: :info) do %>
        If you need to change your payment method or access your invoices, you can do it through the <%= link_to "billing portal", billing_portal_path, class: "underline hover:no-underline" %>.
      <% end %>

      <% if current_user.subscription_pending_cancellation? %>
        <%= render FlashMessageComponent.new(type: :alert) do %>
          Your subscription has been canceled. You will continue to have access to your plan until the end of your billing cycle on 
          <%= current_user.payment_processor.subscription.current_period_end.to_date.strftime("%B %d, %Y") %>.
        <% end %>
      <% end %>    
      
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <% Relay::Billing::Plan.all.select(&:visible).each do |plan| %>
          <div class="flex-shrink-0">
            <%= render(PlanComponent.new(plan: plan, current_user: current_user)) %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>